name: Deploy to Cloud

on:
 
  push:
    branches: [ master ]

jobs:
  
  build:
    name: Deploy to Cloud
    runs-on: ubuntu-latest
    environment: aws
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.6.1
      with:
        playbook: .github/workflows/push-dockerfile.yml
        inventory: |
          172.31.53.77
        key: ${{secrets.SSH_PRIVATE_KEY}}

